### ISSUE TITLE
[calibration] Migrate qibocal routines to use a list of qubits

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#162]

**Comment by maxhant** [comment]
This issue is related to the closed PR #83 which is necessary for multiplex and proper implementation of 2 qubit gates routine. It has already been done by @andrea-pasquale and the live plotting was adjusted by @stavros11. Their code is in the branch https://github.com/qiboteam/qibocal/tree/maxime/add_multiplex_routines.

**Comment by andrea-pasquale** [comment]
Implemented in PR #164 which has been merged to PR #155 that will be soon merged to main.
