### ISSUE TITLE
Hardware sweepers

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibocal#187]
Many platforms support changing parameters such as pulse frequency or amplitude directly on the hardware which is much faster than communicating with the instrument for every point during calibration. The current layout of calibrations in qibocal cannot support this as the sweeps are done in Python loops and I cannot think of any way to translate this to the lower-level languages each platform supports. 

If the parameters that we are sweeping in calibrations are all attributes of the `Pulse` object of qibolab, one possibility that @Jacfomg was proposing was to implement a `platform.execute_pulse_sequences` method that sends a batch of pulse sequences in the device, instead of a single one, as we do now. Apart from calibration and characterization, this may have some use in quantum algorithms so it would be good to implement.

Another approach that may be more elegant for calibrations and thus may be more relevant to qibocal is to use a `Sweeper` object. A simple prototype that I am trying on the QM platform is the following: We define a new object in qibolab

```Python
class Sweeper:

    def __init__(self, parameter, values, pulse=None):
        self.parameter = parameter
        self.values = values
        self.pulse = pulse
```

and a `platform.sweep(sequence, *sweeper, nshots)` which accepts multiple `Sweeper` objects. Then the resonator spectroscopy would look like:

```Python
def resonator_spectroscopy(
    platform: AbstractPlatform,
    qubit: int,
    lowres_width,
    lowres_step,
    highres_width,
    highres_step,
    software_averages,
    points=10,
):

    platform.reload_settings()
    sequence = PulseSequence()
    ro_pulse = platform.create_qubit_readout_pulse(qubit, start=0)
    sequence.add(ro_pulse)

    resonator_frequency = platform.qubits[qubit].characterization.resonator_frequency

    frequency_range = (
        variable_resolution_scanrange(
            lowres_width, lowres_step, highres_width, highres_step
        )
        + resonator_frequency
    )
    fast_sweep_data = DataUnits(
        name=f"fast_sweep_q{qubit}", quantities={"frequency": "Hz"}
    )
    for _ in range(software_averages):
        sweeper = Sweep("frequency", frequency_range, ro_pulse)
        result = platform.sweep(sequence, sweeper)

        while result.in_progress:
            fast_sweep_data.add(result.fetch()) # may add multiple data points at once
            if len(fast_sweep_data) % points == 0:
                yield fast_sweep_data
                yield lorentzian_fit(
                    fast_sweep_data,
                    x="frequency[GHz]",
                    y="MSR[uV]",
                    qubit=qubit,
                    nqubits=platform.settings["nqubits"],
                    labels=["resonator_freq", "peak_voltage", "MZ_freq"],
                )
    yield fast_sweep_data
```

The `platform.sweep` handles how the loop is executed: on hardware if this is possible, otherwise in Python. With some adjustments the `Sweeper` can also support changing parameters that are not pulse attributes, such as `Qubit` or `Channel` attributes.

For live-plotting and live-fitting to work the `result` object should be returned immediately by `platform.sweep` and populated in real time (or in intervals) using `result.fetch()` as the sweep is running on the hardware. This may not be possible for all platforms, however personally I would rather have a fast sweep without live-plotting than a slow sweep with live-plotting. If we really need live feedback in all cases we have to think of a way to send and retrieve the sweeps in batches.

@andrea-pasquale @scarrazza let me know what you think. I think I can implement an example for QM which also supports fetching data in real time during execution. This may not be as crucial as the abstractions but to me is quite urgent, because otherwise our calibration is like doing linear algebra in Python without numpy.

**Comment by andrea-pasquale** [comment]
Thank you @stavros11. I really like this approach, now also the code reads better inside the calibration routine in my opinion. It is also a good thing to move away from python loops because sooner or later they can become a bottleneck.


> The `platform.sweep` handles how the loop is executed: on hardware if this is possible, otherwise in Python. With some adjustments the `Sweeper` can also support changing parameters that are not pulse attributes, such as `Qubit` or `Channel` attributes.

This could be really interesting, in particular for multiplex. In #155 I've implemented the multiplex in the simplest way possible by looping multiple times over the qubits. If we are able to encapsulate some of these for loops in a method that would be great.

Moreover, by having a `platform.sweep` we can avoid to set locally some platform parameters, such as the `LO` or the `IF` since the platform itself will take care of everything.

> For live-plotting and live-fitting to work the `result` object should be returned immediately by `platform.sweep` and populated in real time (or in intervals) using `result.fetch()` as the sweep is running on the hardware. This may not be possible for all platforms, however personally I would rather have a fast sweep without live-plotting than a slow sweep with live-plotting. If we really need live feedback in all cases we have to think of a way to send and retrieve the sweeps in batches.

If the execution becomes very fast we may not even need live-plotting anymore. However, if we can make both things work (the `Sweeper` and `qq-live`) that would be ideal at least in the beginning.

In total we will have 3 different steps in the refactor if I understood everything correctly

1. Refactor the `AbstractPlatform` to work with Qibocal and Qibo and move instruments related methods inside the specific `Platform` inheritance (this is almost done at least a POC)
2. Implement `InstrumentsDesign` approach.
3. Implement custom sweepers for each platform and refactor qibocal accordingly.
