### ISSUE TITLE
Simplifying Ramsey detuned routine

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#273]
There are some issues that were pointed out by @stavros11 in #269 regarding the routine[ `ramsey_frequency_detuned`](https://github.com/qiboteam/qibocal/blob/b48a3f57e25c885de70d3d9606243b9852fc09bd/src/qibocal/calibrations/characterization/ramsey.py#L12).
I think that the main problems are here:

https://github.com/qiboteam/qibocal/blob/b48a3f57e25c885de70d3d9606243b9852fc09bd/src/qibocal/calibrations/characterization/ramsey.py#L183-L209

In particular, this is not robust again multiplex given that if that the variable stop is overwritten by each qubit during the for loop.
Given that we are going towards the autocalibration, I feel like we should aim at simplifying the routine whenever it is possible to avoid bugs.
For this particular routine, I think that instead of looping over different `t_max` we could simplify the routine by fixing a specific `t_max` or `delay_between_pulses_end`, as we are already doing for the standard [`ramsey`](https://github.com/qiboteam/qibocal/blob/b48a3f57e25c885de70d3d9606243b9852fc09bd/src/qibocal/calibrations/characterization/ramsey.py#L230). I don't from an experimental point of view if we gain something by doing everything in a single routine.

Moreover, this should also fix some issues related with a `TODO` concerning the fact that the fitting data are not properly saved.

My idea for the future is that the autocalibration runner could call `ramsey_frequency_detuned` multiple times and it will check whether the current value of T2 is higher or lower compared to the current one available.

I'll implement this change in a separate PR pointing to #269.
Let me know if you agree @aorgazf @DavidSarlle @scarrazza @stavros11 @AleCandido.

**Comment by stavros11** [comment]
> There are some issues that were pointed out by @stavros11 in #269 regarding the routine[ `ramsey_frequency_detuned`](https://github.com/qiboteam/qibocal/blob/b48a3f57e25c885de70d3d9606243b9852fc09bd/src/qibocal/calibrations/characterization/ramsey.py#L12).

Just noting that the issue I had in #269 was with the normal ramsey, not the detuned one.

Regarding the detuned, I have not used it yet and I am not very familiar with what it is doing. I had the impression that you introduce some detuning on the drive frequency (or phase) so that you can see more oscillations in the plot and read a better correction of the qubit frequency. I see that `t_max` is used to calculate this detuning so maybe that is why a double loop is used, in contrast to the normal ramsey where we only sweep the delay between pulses. @DavidSarlle for sure has a better idea how to answer this.
