### ISSUE TITLE
Readout Matrix Routine

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#468]
Hi @DavidSarlle,
A while back we had a routine that we used to call Readout Matrix, that consisted in preparing a set of qubits in all possible states, and then measure them. Due to multiple sources of errors, the states measured will not always correspond to those prepared.
The routine would return a matrix that with the statistical frequencies measured for each state and possible outcome.
We also had applied a color map to each element of the matrix based on the frequency measured.
We know this method does not scale but we could still use to analyse crosstalk between groups of qubits.

**Comment by andrea-pasquale** [comment]
This routine is already implemented in #452 as a separate protocol, in order to run Bell with readout mitigation.
https://github.com/qiboteam/qibocal/blob/bell_protocol/src/qibocal/protocols/characterization/readout_characterization.py
Here is an example
![image](https://github.com/qiboteam/qibocal/assets/49183315/70f02270-be09-4f4d-bc9a-24023265008b)

@aorgazf @DavidSarlle  If you confirm that this routine is what we need we can close this issue.
