### ISSUE TITLE
Protocols docs

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibocal#649]
This issue tracks the documentation of protocols.

- [x]  Resonator Punchout / attenuation #644 
- [x] Resonator spectroscopy / attenuation #575 
- [x]  Qubit spectroscopy / qubit spectroscopy ef 
- [x]  Rabi 
- [x]  Ramsey (see #696 ) 
- [x]  T1
- [x]  T2
- [x]  Zeno
- [x]  Spin echo
- [x]  Single-shot classification/ qutrit classification
- [x]  All-XY
- [x]  Ramsey detuned/ sequences
- [x]  Dispersive shift / Dispersive shift qutrit
- [x]  Flipping
- [x]  Readout mitigation matrix
- [ ]  Coupler routines
- [x]  Fast reset
- [x]  Avoided Crossing
- [x]  Qubit/resonator flux dependencies
- [x]  Qubit/resonator crosstalk
- [x]  Qubit flux tracking
- [x]  RB (Standard, Filtered)
- [x]  Readout optimization
- [ ]  TWPA calibration
- [x]  Time of flight
- [x]  Kernels
- [ ] Chevron
- [ ]  CZ virtualz
- [ ]  CHSH

**Comment by andrea-pasquale** [comment]
Thanks @Edoardo-Pedicillo for opening the issue.
Here are some useful references:

- [Y. Gao, A practical guide for building superconducting quantum devices](https://arxiv.org/pdf/2106.06173.pdf)
- [P. Krantz, A Quantum Engineer’s Guide to Superconducting Qubits](https://arxiv.org/pdf/1904.06560.pdf)
- [M. Baur, Realizing Quantum Gates  and Algorithms with Three Superconducting Qubits](https://qudev.phys.ethz.ch/static/content/science/Documents/phd/PhD_Thesis_Baur_Matthias.pdf)
- [L. Ciociaro, Automatic Single Qubit Routines](https://qudev.phys.ethz.ch/static/content/science/Documents/Bachelor/Livio_Ciorciaro_BachelorThesis_2015.pdf)

Feel free to add other references.

**Comment by rodolfocarobene** [comment]
Hi, I wanted to open an issue regarding documentation, but I see that there is already an open one. 
I will take care of this (at least partially... any help is welcomed). 

I was thinking that even if the protocol description is not very detailed, it's better than nothing. In particular, now it's not easy to understand exactly which all the protocols are and what are the possible parameters for them.

I think this is extremely important to extend the usability of qibocal, in particular when a stable release / publication is on sight. I will try to finish the PR before the end of next week (so that we have a ~ time-limit)

**Comment by Edoardo-Pedicillo** [comment]
https://github.com/qiboteam/qibocal/pull/851#discussion_r1603263812

**Comment by scarrazza** [comment]
Shall we close this?

**Comment by andrea-pasquale** [comment]
> Shall we close this?

I think it is better to wait given that some protocols are missing.
