### ISSUE TITLE
Prevent tests from failing randomly

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#733]
_Originally posted by @andrea-pasquale in https://github.com/qiboteam/qibocal/issues/731#issuecomment-1967436824_

**Comment by alecandido** [comment]
In general, it is good to fix the seed for tests, because they should be reproducible. If you want more randomness, fix many seeds.

Moreover, for tests that depends on the input, sometimes you may want to apply [fuzzing](https://en.wikipedia.org/wiki/Fuzzing).
Hypothesis works quite well, and it is [integrated with Pytest](https://hypothesis.readthedocs.io/en/latest/details.html#the-hypothesis-pytest-plugin) (not only).

https://hypothesis.readthedocs.io/en/latest/
