### ISSUE TITLE
Unintuitive colour scheme used in calssification.py

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#848]
The colour scheme used in `classification.py` asigns red for ground state and blue for ground state. In all papers I read they assign, blue for ground and red for excited state.
![image](https://github.com/qiboteam/qibocal/assets/55031026/142f9567-cee9-4947-a5b0-b40bcbbe879c)

[qibocal/protocols/characterization/utils.py](https://github.com/qiboteam/qibocal/blob/main/src/qibocal/protocols/characterization/utils.py#L430)

I would like to suggest as well to move the legends back to the right of the plot and with fonts consistent with the rest of qibocal routines. The figure could be made slightly larger while still maintaining a normal web page width.

**Comment by Edoardo-Pedicillo** [comment]
> The colour scheme used in `classification.py` asigns red for ground state and blue for ground state. In all papers I read they assign, blue for ground and red for excited state.

The color scheme is not unique in literature (see, for example https://arxiv.org/pdf/2208.05879), by the way, when I refactored the routine, I decided to respect the color scheme that you are proposing for the background.

https://github.com/qiboteam/qibocal/blob/f869f280a966fe8f93ab17c62268ca22c0fa940d/src/qibocal/protocols/characterization/utils.py#L535-L548%C2%A0
 
Regarding the points, the routine is using the default ones since they have high contrast with the background. The points are quite small, and they cannot be bigger to have a decent resolution. When I tried (see https://github.com/qiboteam/qibocal/issues/296#issuecomment-1508524076), the high contrast method was a good compromise to easily discriminate the points from the background.
If you have suggestions about the colors (both points and background), we can consider them. 



> I would like to suggest as well to move the legends back to the right of the plot and with fonts consistent with the rest of qibocal routines. 

This routine is supposed to run with different classifiers, and the report displays all the results in the same raw. If the legends are on the right, it is quite difficult to put all the plots in a row, considering the legend size, so for the moment it will not be implemented. 

> The figure could be made slightly larger while still maintaining a normal web page width.

For sure, I can try to center and increase the size of the plots. By the way, we have already discussed these details in #296.
