### ISSUE TITLE
Running `qq report` after `qq upload` fails

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#934]
I think that the error is related to the fact that after upload the `meta.json` will contain also an `author` field.
It should be easy to fix. To reproduce the error it should be sufficient to run `qq report <output>` when `<output>` was previously uploaded using `qq upload <output>`.

**Comment by alecandido** [comment]
It's to fix: now that there is a `Metadata` object
https://github.com/qiboteam/qibocal/blob/347a7b96908aaa3eb89cbbf785829a89801f69c9/src/qibocal/auto/output.py#L42-L52
all the fields that will ever be available in `meta.json` should be in there, possibly set by default to `None`.

If the fields are there, they will always be available, and we only have to face "one case" (ok, it could be `None`, but at least is there), instead of dealing with multiple states of `meta.json`.
